### ISSUE TITLE
Does not work on latest RC

### ISSUE THREAD

**Issue by eashman** [sjelfull/craft-audit#20]
Once added to composer, the admin tool will not load without errors even after activation

**Comment by eashman** [comment]
After reinstalling from scratch (deleting the Vendor dir and re-running composer), the site does load now but nothing gets put into the Audit view.  Not sure how you debug this kind of thing.

**Comment by sjelfull** [comment]
Sounds weird. It hopefully should show something in web.log. Could you see if you find the errors from earlier there?

Could you also try to replicate this on another server?

**Comment by sjelfull** [comment]
I was able to reproduce this, and i'm currently working to figure out what is causing this.

**Comment by sjelfull** [comment]
Could you pull down the latest version and try again?

**Comment by sjelfull** [comment]
It seems the error has been resolved, so i'm closing this now. Let me know if it still happens with the latest version.
